---
- name:           Determine optimal hostname
  command:        echo ${stage}.${domain}
  register:       new_host
  ignore_errors:  True

- name:           Determine current hostname
  command:        hostname
  register:       old_host
  ignore_errors:  True

- name:           Update current hostname
  command:        hostname ${new_host.stdout}
  sudo:           yes
  when:           old_host.stdout != new_host.stdout

- name:           Update canonical hostname
  copy:           content=${new_host.stdout} dest=/etc/hostname
  sudo:           yes
  when:           old_host.stdout != new_host.stdout

- name:           Update /etc/hosts for new hostname
  command:        perl -p -i.bak -e s/${old_host.stdout}/${new_host.stdout}/ig /etc/hosts
  sudo:           yes
  when:           old_host.stdout != new_host.stdout

- name:           Add Node apt-repository
  apt_repository: repo='ppa:chris-lea/node.js' state=present
  sudo:           yes

- name:           Update apt repositories
  apt:            update_cache=yes
  sudo:           yes

- name:           Install system packages
  apt:            pkg=${item}
  with_items:     ${system_packages}
  sudo:           yes

- name:           Install bower
  command:        npm install -g bower
  sudo:           yes

- name:           Install LAMP stack
  shell:          DEBIAN_FRONTEND=noninteractive tasksel install lamp-server
  sudo:           yes

- name:           Install PHP packages
  apt:            pkg=${item}
  with_items:     ${php_packages}
  sudo:           yes

- name:           Enable Apache modules
  command:        a2enmod ${item}
  with_items:     ${apache_modules}
  sudo:           yes

- name:           Check for vagrant user
  command:        id -u vagrant
  register:       has_vagrant
  ignore_errors:  True

- name:           Add vagrant user to www-data
  user:           name=vagrant append=yes groups=www-data
  when:           has_vagrant.stdout
  sudo:           yes

- name:           Update php.ini's memory_limit
  lineinfile:     dest=/etc/php5/apache2/php.ini backup=yes regexp='memory_limit' line='memory_limit = 1024M'
  sudo:           yes

- name:           Update php.ini's date.timezone
  lineinfile:     dest=/etc/php5/apache2/php.ini backup=yes regexp='date\.timezone' line='date.timezone = "America/Chicago'
  sudo:           yes

- name:           Update my.conf's bind-address
  lineinfile:     dest=/etc/mysql/my.cnf backup=yes regexp=^bind-address line='bind-address = 0.0.0.0'
  sudo:           yes

- name:           Create deploy user
  user:           name=deploy append=yes groups=www-data shell=/bin/bash comment="Created by Genesis WordPress"
  sudo:           yes

- name:           Grant sudo access to deploy user
  copy:           content="%deploy ALL=(ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/deploy mode=0440 force=no
  sudo:           yes
